### PR TITLE
Split Error Enum to separate errortypes.py file; improve Error thingy

### PR DESCRIPTION
**Pull request by Zephia-Sero**

### CODE REVIEW

**Comment by lemonlambda** [comment]
Name it and give it label please

**Comment by Zephia-Sero** [comment]
might be broken if you use Error anywhere other than parser.py

**Comment by lemonlambda** [comment]
Setup errortype.py correctly to comply to the

**Comment by lemonlambda** [comment]
Make

**Comment by lemonlambda** [comment]
Make

**Comment by lemonlambda** [comment]
Make errortype.py comply with examplefile.py

**Pull request closed without merging**
